### ISSUE TITLE
Gulp build --env prod skips making production files

### ISSUE THREAD

**Issue by FossPrime** [bezoerb/generator-sf#49]
gulp build --env prod is not generating main.css or main.js and the php templates are the initial ones, not my modified ones. 

Any ideas? I'm on node 6.10 on php 7

app_dev.php works fine, gulp serve works fine

P.S. I'm in a hackathon... I'm working around it by running a production mode php-middleware server.

THANKS!

**Comment by bezoerb** [comment]
Thanks for reporting @rayfoss.
I'll try to take a look this weekend.

**Comment by bezoerb** [comment]
@rayfoss: Just tried and it generates the files. 
```
├── scripts
│   ├── main-c63d694f74.js
│   └── sw
│       ├── runtime-caching.js
│       └── sw-toolbox.js
├── service-worker.js
└── styles
    ├── critical
    │   └── default
    │       └── index.css
    └── main-57172a2820.css
```

Can you give some hints to reproduce your error with clean generated project? E.g. the generator options you used?

**Comment by FossPrime** [comment]
I managed to reproduce it on another computer. 

# Steps to reproduce
1. install with the settings below
2. make a css change, like adding `.panel {background: #f00;}`
3. run gulp build
4. load the site without running `gulp serve --env prod` in between... which is also a fine workaround.

# result 

![screenshot from 2017-04-08 06-33-43](https://cloud.githubusercontent.com/assets/876076/24828565/6b7b4e0a-1c25-11e7-89d0-b60529d33045.png)

Settings used:
```
Gulp
sass
node-sass
webpack
UnCss: On
Critical: On
Git: On
```

```
$ node -v
v7.8.0
$ php -v
PHP 5.6.29 (cli) (built: Dec  8 2016 09:17:12) 
```

P.S. The critical JS settings seem to conflict with foundation-sites, it renders a tablet version of the nav on desktop #firstworldproblems

**Comment by FossPrime** [comment]
The problem is with the rendered html not the files generated. The rendered HTML points to main.css not the minified version, when you run `build` without `serve` first. 

Update: may have something to do with NUTTY acl/permissions conflicts in the /var/prod folder that seem to occur when apache runs it, vs the built in node server. Still would be nice to get warnings in the build log

**Comment by FossPrime** [comment]
will write a pull request to trigger `bin/console cache:clear -e prod` on gulp clean

I don't believe all the cache goes to var/node when running `gulp serve --env prod` forcing that would also mitigate issues. I'm also having the same difficult to fix routing issues with the node server that I had in the `symfony-grunt-generator` days.

There's work to be done... still awesome though!
